# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160701_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_descripton',
            field=models.CharField(default='', max_length=400),
        ),
    ]
